function opts = getOptsStruct()
%getOptsStruct Structure used to parse wvd and xwvd inputs

%   For internal use only. 
    
%   Copyright 2018 MathWorks, Inc.

opts = struct(...    
    'DataLength', [], ...
    'IsSingle', false, ...
    'TimeUnits', '', ...
    'InitialDate', [], ...
    'TimeMode', 'samples', ...
    'EffectiveFs', [], ...
    'IsNormalizedFreq', false, ...
    'NumTimePoints', [], ...
    'NumFrequencyPoints', [], ...
    'TimeVector', [], ...
    'Type', 'wvd', ...
    'TimeWindow', [], ...
    'FrequencyWindow', [], ...
    'MinThreshold', []);
end